name: vision_mate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^2.0.10
  image: ^4.3.0 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.jpg"

  flutter_lints: ^4.0.0
  
flutter:

  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 100

  assets:
    - assets/icons/logo.jpg
    - assets/icons/password_svg.svg
    - assets/icons/email_svg.svg
    - assets/icons/dropdown_arrow.svg
    - assets/images/fairtrade_logo.svg
    - assets/images/Splash Screen bg.svg
    - assets/images/Background.svg
    - assets/images/banner.svg
    - assets/images/banner_image.png
    - assets/images/Banner_OverLay.png
    - assets/images/farmers_guidline.png
    - assets/images/profile_image.svg
    - assets/images/profile_image.jpg
    - assets/images/rice_producer.svg
    - assets/images/profiltibility.jpg
    - assets/images/farmers.png
    - assets/images/manage_forms.jpg
